### ISSUE TITLE
why ref.current is undefined in useEffect?

### ISSUE THREAD

**Issue by ChaiGuangJie** [trash-and-fire/lightweight-charts-react-wrapper#22]
<img width="449" alt="屏幕截图 2024-06-06 024405" src="https://github.com/trash-and-fire/lightweight-charts-react-wrapper/assets/8953006/e3893e97-6e78-4e14-a306-258691b00d8d">

**Comment by ChaiGuangJie** [comment]
return (<Chart width={400} height={300} ref={myRef} />)

**Comment by ChaiGuangJie** [comment]
<img width="449" alt="屏幕截图 2024-06-06 024405" src="https://github.com/trash-and-fire/lightweight-charts-react-wrapper/assets/8953006/780ef28b-a30b-413e-8707-01ae6f1e5679">

**Comment by trash-and-fire** [comment]
This is a fundamental limitation in the interaction between react and the chart library. The chart library requires a dom element for initialization, and I can only get it in the effects phase, so references are initialized only after the second render of the internal components. At the moment I haven't figured out how to get around this limitation.

As workaround you can use following code:
```
function Component() {
   const [ref, setRef] = useState(null);
   
   useEffect(() => {
       if (ref) console.log(ref);
   }, [ref]);
   
   return <Chart width={400} height={300} ref={setRef}/>
}
```

I'd like to know a little more about your case. Could you please explain what you are going to do with the ref in the effect.

**Comment by ChaiGuangJie** [comment]
Thanks. That's enough for me！
