### ISSUE TITLE
HistogramSeries does not render as a subcomponent

### ISSUE THREAD

**Issue by Abcold** [trash-and-fire/lightweight-charts-react-wrapper#4]
I want to use HistogramSeries as a sub component, but when I use use state in the parent component and then pass the value, HistogramSeries does not render, even though the value has been updated

<img width="862" alt="截屏2022-11-04 下午6 22 09" src="https://user-images.githubusercontent.com/37355225/199950123-badc6aa6-d6b8-446f-9309-e2bac38c462e.png">

**Comment by trash-and-fire** [comment]
https://github.com/trash-and-fire/lightweight-charts-react-wrapper#passing-data
> By default data represents only the initial data. Any subsequent data update does not update series. If you want to change this behavior please add reactive={true} to your series component. In this case series will apply a new data if it is not reference equal to previous array.

This works perfectly https://codesandbox.io/s/dynamic-volume-tv7ckc?file=/example.tsx

**Comment by Abcold** [comment]
It worked, thank you
