### ISSUE TITLE
add multiple panes support in the future？

### ISSUE THREAD

**Issue by Abcold** [trash-and-fire/lightweight-charts-react-wrapper#5]
I want to use both CandlestickSeries and HistogramSeries in a chart, just like bybit. 
Are there opportunities to expand and add multiple panes support in the future？
https://www.bybit.com/en-US/trade/spot/BTC/USDT
reference： https://github.com/tradingview/lightweight-charts/issues/50

**Comment by trash-and-fire** [comment]
I will support any new features as soon as they are implemented in the base package. But I have no information about when they will be implemented.

**Comment by Abcold** [comment]
got it , thanks a lot.
