### ISSUE TITLE
Add Series Marker

### ISSUE THREAD

**Issue by cmjacques** [trash-and-fire/lightweight-charts-react-wrapper#6]
Hi there, thanks for this library.

I'd like to make a feature request - add support for Series Markers as per https://tradingview.github.io/lightweight-charts/tutorials/how_to/series-markers

I don't believe this is possible right now?

**Comment by trash-and-fire** [comment]
It is possible through the `ref` https://codesandbox.io/s/codesandboxer-example-forked-wyy73i?file=/example.tsx. 

I will add a declarative api to handle this in future. Something like `<LineSeries data={data} markers={markers}/>`.

**Comment by cmjacques** [comment]
Excellent - thanks for the fast reply and solution 👍

**Comment by trash-and-fire** [comment]
Done in 2.0.0
