### ISSUE TITLE
PriceScale `scaleMargins` doesn't work

### ISSUE THREAD

**Issue by cjkoepke** [trash-and-fire/lightweight-charts-react-wrapper#9]
The `PriceScale` component does not update the actual price scale of the matching Series.

```ts
<Chart
            handleScale={{
              axisDoubleClickReset: true,
            }}
            timeScale={{
              timeVisible: true,
              fixLeftEdge: true,
              fixRightEdge: true,
              lockVisibleTimeRangeOnResize: true,
            }}
          >
<HistogramSeries
  priceScaleId="right"
  priceFormat={{
    type: "volume",
  }}
  data={volumeData ?? []}
/>
<PriceScale
  id="right"
  scaleMargins={{
    top: 0.8,
    bottom: 0
  }}
/>
</Chart>
```

**Comment by trash-and-fire** [comment]
looks like a bug. I'll see what could be the problem.

**Comment by trash-and-fire** [comment]
What version of react and lightweight-charts are you using?

**Comment by trash-and-fire** [comment]
Try using as workaround:
```
<Chart
    rightPriceScale: {
        scaleMargins={
            top: 0.8,
            bottom: 0
        }
    }
>
 ```

**Comment by cjkoepke** [comment]
I would try using the top-level default settings, but I have two charts and need them to have independent scale margins. My example was just for brevity as it doesn't seem to matter how many there are.

React: `18.2.0`
Lightweight Charts: `4.0.1`

**Comment by trash-and-fire** [comment]
Try using 1.3.3. There should be a fix.

**Comment by cjkoepke** [comment]
> Try using 1.3.3. There should be a fix.

This fixed the issue! Thanks for the quick response.
